practice-for-ch-rails-music-app-long-practice-main/music_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/models/user.rb
class User < ApplicationRecord
    validates :email, :password_digest, :session_token, presence: true
    validates :email, :session_token, uniqueness: true 
    validates :password, length: {minimum: 6}, allow_nil: true 
    before_validation :ensure_session_token

    attr_reader :password

    def generate_unique_session_token
        loop do 
            session_token = SecureRandom::urlsafe_base64
            return session_token unless User.exists?(session_token: session_token)
        end
    end

    def reset_session_token!
        self.session_token = generate_unique_session_token
        self.save!
        self.session_token
    end 

    def ensure_session_token
        self.session_token ||= generate_unique_session_token
    end 

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end 

    def is_password?(password)
        pass_obj = BCrypt::Password.new(self.password_digest)
        pass_obj.is_password?(password)
    end 

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        return nil if !user
        user.is_password?(password) ? user : nil
    end 

end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_forgery_protection
    helper_method :current_user, :logged_in?

    def current_user
        return nil unless session["session_token"]
        @current_user = User.find_by(session_token: session["session_token"])
    end 

    def login!(user)
        session["session_token"] = user.reset_session_token!
        @current_user = user 
    end 

    def logout!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end 

    def logged_in?
        !!current_user
    end 

    def require_logged_out
        
    end 
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
        render :new
    end 

    def create
        @user = User.find_by_credentials(params["user"]["email"], params["user"]["password"])
        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            render :new 
        end 
    end

    def destroy
        logout!
        redirect_to new_session_url
    end 
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            login!(@user)
            redirect_to user_url(@user)
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end 

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end 
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/helpers/users_helper.rb
module UsersHelper
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <% if logged_in? %>
      <h1>Welcome <%= current_user.email %></h1>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Logout">
      </form>
    <% else %>
        <a href="<%= new_session_url %>">Login</a>
        <a href="<%= new_user_url %>">Sign Up</a>
    <% end %>
    <%= yield %>
  </body>
</html>

practice-for-ch-rails-music-app-long-practice-main/music_app/app/views/users/new.html.erb
<h1>User Sign Up Form</h1>


<form action="<%= users_url %>" method="POST">
    
    <label>Email
        <input type="text" name="user[email]" value="">
    </label>

    <br>
    <br>

    <label>Password
        <input type="password" name="user[password]" value="">
    </label>

    <br>
    <br>

    <input type="submit" value="Sign Up">

</form>

practice-for-ch-rails-music-app-long-practice-main/music_app/app/views/users/show.html.erb
<h1>User Details</h1>

<p>Email: <%= @user.email %></p>